version: '3'

services:
  whoami:
    image: containous/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.shanyue.tech`)"
    # environments:
    #   TMUX
    
networks:
  default:
    external:
      name: traefik_default
